### PR TITLE
clarify available for python

### PR DESCRIPTION
**Pull request by Borda**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

## What does this PR do?

While using it in Bolts, I noticed that it could be misleading as you can also ask if PyTorch module is available...

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by akihironitta — APPROVED** [review]

**Review by carmocca — CHANGES_REQUESTED** [review]
I dont understand the motivation. How is a PyTorch module not a Python module?

**Comment by Borda** [comment]
> I dont understand the motivation. How is a PyTorch module not a Python module?

if you read a code and someone is calling/using `module_available` do you know if it `nn.Module` or a general Python module/package?

**Comment by carmocca** [comment]
It can be inferred from context: the import path, the arguments, docstrings etc.

If you still want to rename it, the current proposal is still ambiguous, I would instead choose `import_path_available`, however you need to consider that this would be a breaking change and that our projects that already use it will need to be updated too

**Comment by Borda** [comment]
> however you need to consider that this would be a breaking change and that our projects that already use it will need to be updated too

We have pin version anyway :otter:

**Pull request closed without merging**
